### ISSUE TITLE
Theming the dialog

### ISSUE THREAD

**Issue by JcDenton86** [EddyVerbruggen/cordova-plugin-actionsheet#14]
Hi, Android dialog can also be themed either with predefined themes (http://developer.android.com/reference/android/app/AlertDialog.html) or by creating a custom xml theme. I am using this plugin and changed it to accept one more int option so to choose the theme too. 
Maybe this should be added as a default in the plugin, because the alert dialog that is shown does  not follow the new design of the Android OS and the application.

**Comment by thco** [comment]
Totally agree, it looks like very old on Lollipop devices ... +1 for this !

**Comment by EddyVerbruggen** [comment]
Hi guys, I've implemented this feature in 1.1.2, please check it out!
The default is still what it was, but [you can override it](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet/blob/master/demo/index.html#L37).

Thanks,
Eddy

**Comment by thco** [comment]
Seems to be awesome :) nice feature ! Thanks.

**Comment by EddyVerbruggen** [comment]
:+1:

**Comment by thco** [comment]
Great. Thank you.

**Comment by JcDenton86** [comment]
:+1:

**Comment by srameshr** [comment]
```
window.plugins.actionsheet.ANDROID_THEMES.THEME_DEVICE_DEFAULT_LIGHT
```
This still gives me the same old holo them action, even though I am running on Lollipop.

**Comment by EddyVerbruggen** [comment]
Just to be sure: if you do `alert('theme: ' + window.plugins.actionsheet.ANDROID_THEMES.THEME_DEVICE_DEFAULT_LIGHT) does it resolve correctly?

**Comment by srameshr** [comment]
Yes it does.
Here is my options object:
```
var options = {
        'androidTheme':  window.plugins.actionsheet.ANDROID_THEMES.THEME_DEVICE_DEFAULT_LIGHT,
        'title': 'SELECT PICTURE FROM',
        'buttonLabels': ['CAMERA', 'GALLERY'],
        'androidEnableCancelButton' : true, // default false
        'winphoneEnableCancelButton' : true, // default false
        'addCancelButtonWithLabel': 'Cancel',
        'position': [20, 40] // for iPad pass in the [x, y] position of the popover
    };
```

**Comment by EddyVerbruggen** [comment]
I get three different style when:

1. not passing in androidTheme
2. using window.plugins.actionsheet.ANDROID_THEMES.THEME_HOLO_LIGHT
3. window.plugins.actionsheet.ANDROID_THEMES.THEME_DEVICE_DEFAULT_LIGHT

The only thing I can think of is you're trying to resolve the variable before `deviceready` fires. Does it change if you pass in the numbers 1 through 5 instead, where 5 is the one you were trying to use?

**Comment by srameshr** [comment]
I am invoking it inside of device ready. Tried that too. Does not seem to be working. Using numbers for androidTheme has no effect. 5 which I am using for a datePicker shows up material design. But the action sheet is still on the holo theme.

**Comment by EddyVerbruggen** [comment]
So using 1, 2 or 5 yields the same result? What plugin version do you use?

**Comment by srameshr** [comment]
https://github.com/VitaliiBlagodir/cordova-plugin-datepicker
This is the date picker plugin that I am using. When I set ```androidTheme``` value to ```5```, material design date picker shows up.

**Comment by EddyVerbruggen** [comment]
Which plugin version?

**Comment by srameshr** [comment]
Sorry, I did not understand that. I am just pulling the latest stable version from cordova. 
```cordova plugin add plugin_package```

**Comment by EddyVerbruggen** [comment]
@srameshr If you want any more assistance please send me your project at eddyverbruggen at gmail dot com.

**Comment by srameshr** [comment]
@EddyVerbruggen Wow! Thanks for being so awesome!
 But I used a javascript UI widget to get the job done. 
But once again thank you for asking :)
