### ISSUE TITLE
Deprecations in ActionSheet.m

### ISSUE THREAD

**Issue by alxpereira** [EddyVerbruggen/cordova-plugin-actionsheet#15]
Hi,
It looks like there's some deprecated methods (since Cordova 3.6) used in the iOS ActionSheet file.
This doesn't affect the fonctionnality, but it could be nice to use the latest methods to be sure that Cordova updates won't break your cool plugin.

![screen shot 2015-02-27 at 18 29 34](https://cloud.githubusercontent.com/assets/447895/6417618/d10c3ce2-beae-11e4-8dde-ba14bd0e64ed.png)

**Comment by EddyVerbruggen** [comment]
Thanks for noticing, they're gone now!

Best,
Eddy
