### ISSUE TITLE
Android Lolipop style action sheet?

### ISSUE THREAD

**Issue by djett41** [EddyVerbruggen/cordova-plugin-actionsheet#18]
Hello! great plugin.  Will the action sheet always reflect the OS design for previous, current, and future releases?

for example, the action sheet is no longer an inset popup for Lolipop and looks like the following.. Will this new UI design require an update to this plugin?  Or will running the plugin at its current version look like the design below?

http://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-specs 

Thanks!!!

**Comment by EddyVerbruggen** [comment]
Hi,

I don't think the 'Bottom sheet' is the same as the 'AlertDialog' the plugin currently uses for Android. You can make sure that the AlertDialog is properly styled by passing in the correct 'theme' ([I recently added this option](#14)).

To really support the new Bottom sheet the plugin would need an update indeed, but it's not planned at the moment.

Best,
Eddy

**Comment by djett41** [comment]
Thanks for the quick response!  Exactly what I was looking for.  thnaks

**Comment by rayshan** [comment]
FYI Android Support Library 23.2 introduced official support for Bottom Sheets: http://android-developers.blogspot.com/2016/02/android-support-library-232.html
