### ISSUE TITLE
Cache actionsheet instance

### ISSUE THREAD

**Issue by chemerisuk** [EddyVerbruggen/cordova-plugin-actionsheet#19]
Hi @EddyVerbruggen. I noticed that for long list of items showing the menu might have a noticable delay. Is is possible to cache an actionsheet instance in memory to improve performance? If yes, how it can be applied to API?

**Comment by EddyVerbruggen** [comment]
Hi, on which platform are you seeing this issue, and how many items are you showing?
Perhaps you can share even a bit of code?

Thx,
Eddy

**Comment by chemerisuk** [comment]
Hi @EddyVerbruggen. It has delay on both platforms, but the most noticeable is on iOS (because of animation I guess).

Below is the config object I pass into `actionsheet.show` (strings are not in english, sorry):

```
{
    "title": "",
    "buttonLabels": [
        "Автозавод",
        "Боровляны",
        "Брилевичи",
        "Бульвар",
        "Велозавод",
        "Веснянка",
        "Вокзал",
        "Восток",
        "Дражня",
        "Ждановичи",
        "Запад",
        "Зеленый луг",
        "Калинина",
        "Камвольный",
        "Каменная горка",
        "Комаровка",
        "Корона",
        "Кунцевщина",
        "Курасовщина",
        "Лошица",
        "Малиновка",
        "Масюковщина",
        "Маяк",
        "Новинки",
        "Озерище",
        "Победа",
        "Порт",
        "Прилуки",
        "Пушкина",
        "Розочка",
        "Сельхозпоселок",
        "Сенница",
        "Серебрянка",
        "Сухарево",
        "Тракторный завод",
        "Уручье",
        "Чижовка",
        "Шабаны",
        "Шарики",
        "Юбилейка",
        "Юго-запад"
    ],
    "androidTheme": 3,
    "addCancelButtonWithLabel": "Назад",
    "androidEnableCancelButton": true
}
```

**Comment by EddyVerbruggen** [comment]
Holy cow!

I'm not sure an ActionSheet is meant for that many elements.. it's even discouraged by [Apple's guidelines](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html) (Users shouldn't need to scroll in ActionSheets).

Perhaps you're better off using a picker instead?

**Comment by chemerisuk** [comment]
Thanks for feedback @EddyVerbruggen. The problem with picker is that it's a full screen menu (unlike on Android). And I haven't found any issue with accidental taps on items in my case...

Anyway, if Apple doesn't recommend to use long lists for such control - I should close this issue probably.

**Comment by EddyVerbruggen** [comment]
Note that I did try to provide a cached version as you suggested but it only helped about 20% or so. As it seems the problem is not building the list but drawing it. A long list like this needs a scroll-wrapper which seems to be the thing causing the performance penalty.

**Comment by chemerisuk** [comment]
@EddyVerbruggen 

May be you could provide an option to disable animation? It will be displayed faster without it.

**Comment by EddyVerbruggen** [comment]
If you control the native code, you could try it by changing [this line](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet/blob/master/src/ios/ActionSheet.m#L35) to:

```
      [actionSheet showFromRect:self.webView.frame inView:self.webView.superview animated:false];
```

**Comment by chemerisuk** [comment]
@EddyVerbruggen thanks, I'll try it!
