### ISSUE TITLE
Crashes the app on iOS after cordova update

### ISSUE THREAD

**Issue by oguzgelal** [EddyVerbruggen/cordova-plugin-actionsheet#33]
Hello.

I have been using this plugin, however after I do a little update on cordova, ionic-cli, ionic platform, other plugins etc. (not sure which one is causes it), it started to crash the app on ios.

When action sheet code gets executed, the app freezes. After running the app on iOS, I realised that it seems to enter an infinite loop (see image below).

![screen shot 2016-01-14 at 05 04 06 2](https://cloud.githubusercontent.com/assets/2817993/12314726/534201dc-ba7c-11e5-9fe5-10d2e04fd9c5.png)

**Comment by EddyVerbruggen** [comment]
So you think it may be a combination of the things your app uses? That may be the case, so can you please share that Xcode project with us? Or at least a stripped version which reproduces this crash. Thx!

**Comment by oguzgelal** [comment]
I'm not authorised to share any codes of the project. However, I can do this:

```
ADMIN-MAC:syndcate-client oguzgelal$ ionic --version
1.7.12

ADMIN-MAC:syndcate-client oguzgelal$ cordova --version
5.4.1
ADMIN-MAC:syndcate-client oguzgelal$ cordova plugins
com.googlemaps.ios 1.11.1 "Google Map iOS SDK for Cordova"
cordova-plugin-actionsheet 2.2.0 "ActionSheet"
cordova-plugin-app-event 1.1.0 "Application Events"
cordova-plugin-camera 1.2.0 "Camera"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.1.0 "InAppBrowser"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-whitelist 1.2.0 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 1.0.6 "Keyboard"
org.apache.cordova.dialogs 0.3.0 "Notification"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
phonegap-plugin-push 1.5.2 "PushPlugin"
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"
ADMIN-MAC:syndcate-client oguzgelal$
```

App crashes on iPhone 5 - iOS 9.2 (Also on  emulator with iOS 9.2)

**Comment by EddyVerbruggen** [comment]
I see, can you create a new app with those plugins and a button which recreates the issue?

**Comment by oguzgelal** [comment]
Okay I'll do it. I'll ping here when its ready. Thanks!

**Comment by aks0020** [comment]
:+1: same here crashed on fresh ionic project with latest cordova

**Comment by EddyVerbruggen** [comment]
@aks0020 does it also crash on a fresh non-ionic project?

**Comment by aks0020** [comment]
@EddyVerbruggen actually it works `cordova-plugin-app-event` was causing issue on swizzled_plugin init. Sorry.

**Comment by inexuscore** [comment]
I still have this issue. using cordova-plugin-file-transfer v1.7.0 on an Ionic v1 project. everything works flawlessly when targeting my local dev machine, but when I target our remote production server, file uploads complete, but then crash the app unexpectedly. any ideas?
