### ISSUE TITLE
Unicode characters not working

### ISSUE THREAD

**Issue by Randgalt** [EddyVerbruggen/cordova-plugin-actionsheet#35]
Spanish characters are getting corrupted.

```
        var options = {
            'buttonLabels': ['Español', 'Inglés'],
            'addCancelButtonWithLabel': 'Cancelar'
        };        

        window.plugins.actionsheet.show(options, app.optionsCallback);
```

<img width="316" alt="screen shot 2016-02-15 at 5 33 56 pm" src="https://cloud.githubusercontent.com/assets/264818/13062152/62aa1180-d40a-11e5-9850-bd3abf8ca9db.png">

**Comment by Randgalt** [comment]
Note: this is the iOS emulator. I haven't tried Android.

**Comment by EddyVerbruggen** [comment]
Hi, thanks for the details! Indeed it didn't look good on iOS. Did you check Android as well? If you find an issue there please let me know.

Version 2.2.1 is now available, and it renders fine:

![img_6345](https://cloud.githubusercontent.com/assets/1426370/13071966/14976de8-d497-11e5-9d2e-494bdc0eae0d.PNG)

**Comment by EddyVerbruggen** [comment]
So in the end it turns out you just need to add this to your index.html:

```
<meta charset="utf-8" />
```

Then you don't need to encode anyhting and mix spanish, cyrillic, whatnot just nicely.
