### ISSUE TITLE
Crash when use cyrillic (non-latin) title

### ISSUE THREAD

**Issue by KODerFunk** [EddyVerbruggen/cordova-plugin-actionsheet#36]
Crash in `encodeString` https://github.com/EddyVerbruggen/cordova-plugin-actionsheet/blob/master/src/ios/ActionSheet.m#L67

Fix in project localy by change `NSISOLatin1StringEncoding` => `NSUTF8StringEncoding` in `cStringUsingEncoding` call.

Used title: `Откуда взять фото?`

**Comment by EddyVerbruggen** [comment]
Interesting - if I use that I don't get `Откуда взять фото?` but an encoded version.. I had to change this for #35, but indeed yours crashes. Any ideas?

**Comment by KODerFunk** [comment]
Try spain words with my trick (without `NSISOLatin1StringEncoding`). If it work — it must be fixed!)

**Comment by EddyVerbruggen** [comment]
I did but it didn't work for me. Perphaps I have the syntax wrong?

**Comment by KODerFunk** [comment]
Can it been auto-tested?

**Comment by EddyVerbruggen** [comment]
I'm simply trying it like this:

```js
        function testShareSheet() {
          var options = {
            'title': 'Откуда взять фото?',
            'buttonLabels': ['Español', 'Inglés'],
            'addCancelButtonWithLabel': 'What\'s Español?',
            'addDestructiveButtonWithLabel' : 'Remove Inglés'
          };
          window.plugins.actionsheet.show(options, function(){});
        };
```

And the result with 
```
[NSString stringWithCString:[input cStringUsingEncoding:NSUTF8StringEncoding] encoding:NSUTF8StringEncoding];
```
(which is the same as not encoding it at all) is:
<img width="374" alt="screen shot 2016-02-16 at 19 15 53" src="https://cloud.githubusercontent.com/assets/1426370/13086075/c8e0451e-d4e1-11e5-8177-48188a831579.png">

Do you see a similar result?

I'm going to roll my last change back so your case works again, but Spanish will break again. Ideas?

**Comment by KODerFunk** [comment]
I try use your options in my app http://take.ms/NduTs with my dirty-fix:

![my UTF8-trick](https://api.monosnap.com/rpc/file/download?id=0FIPmkv0UDPIIwSfaan2rf7ee0KQTh)

Then I return [`NSISOLatin1StringEncoding`](http://take.ms/PnkWV), `cordova run ios ...`, `tap..tap...tap`, crash! Crashshot: http://take.ms/oNPsj

Could this be due to the fact that all my sources utf8-encoded and `<meta charset="utf-8" />` in `index.html/head`?
System and phone locale is `ru`/'ru-RU'.

**Comment by EddyVerbruggen** [comment]
Ha, that's it!

You just need to add `<meta charset="utf-8" />` meta tag and all encoding is just fine. So the 2.2.2 release should work fine for you with that tag added, thanks for the pointer!

**Comment by KODerFunk** [comment]
Thank You, Eddy!

**Comment by martinjbaker** [comment]
Not working for me with 2.2.2. I have `<meta charset="utf-8" />` in index.html and any non-ASCII characters in buttonLabels are crashing the app. I have bullet points to denote which option is currently active.

    buttonLabels: ['Closing Date', '• Average Critic Rating •']

**Comment by EddyVerbruggen** [comment]
@martinjbaker Works fine on my sim and device (see screenshot).

Can you try removing the iOS platform and adding it again, same for the plugin? And make sure the html/js files are UTF-8 encoded as well.

<img width="374" alt="screen shot 2016-02-19 at 20 25 47" src="https://cloud.githubusercontent.com/assets/1426370/13186571/15a331ce-d747-11e5-9b67-aa884b6080ec.png">

**Comment by martinjbaker** [comment]
Yep that fixed it, thanks.
