### ISSUE TITLE
Position of destructive button

### ISSUE THREAD

**Issue by Hirbod** [EddyVerbruggen/cordova-plugin-actionsheet#40]
Hi @EddyVerbruggen,

the destructive button is always on first position, even when added later to the options array. Is there any way to decide where to show it? Or at least to put it at bottom?

**Comment by Hirbod** [comment]
Sorry, forgot to mention. It's on iOS

**Comment by EddyVerbruggen** [comment]
According to [this SO answer](http://stackoverflow.com/questions/6353709/how-to-change-sequence-of-button-in-uiactionsheet-in-iphone) that should be possible. I hope to add a preference soon.

**Comment by Hirbod** [comment]
This would be perfect. It would be awesome to also provide something like

destructiveButtonIndex = integer
or
destructiveButtonIndex = "first"; (default)
destructiveButtonIndex = "last";

This would save us time calculating the offset (just a nice to have, as ActionSheets usally dont have more then 3-5 items.

**Comment by EddyVerbruggen** [comment]
I'm refactoring the iOS code as we speak because I'm using a class that's been deprecated since iOS8.. and with iOS10 on our doorstep I don't have an excuse not to move on. I will try to maintain backward compat with iOS7 and lower though.

Note that the appearance of the ActionSheet will not change for iOS, it's mostly an internal thingy in iOS' codebase.

@Hirbod I'll take that request into account and provide a new `destructiveButtonLast` boolean property which is default `false` so it's the same as it is now (per your suggestion).

**Comment by EddyVerbruggen** [comment]
Available in 2.3.0 on all platforms. See the updated example in the readme (look for `destructiveButtonLast`).

**Comment by Hirbod** [comment]
Wow.. this was, again, @EddyVerbruggen light speed development. Guess I will send some beer again.

**Comment by EddyVerbruggen** [comment]
Good. My stock dried up in the meanwhile! Cheers mate 🍻

**Comment by Hirbod** [comment]
@EddyVerbruggen while the combination with destructiveButtonLast works pretty good, single ActionSheets (with just one option) don't work anymore on 2.3.0. I don't even receive an error or something. I will try to find out if "destructiveButtonLast" is causing this or not.

**Comment by Hirbod** [comment]
Identified the bug.

```
    var options = {
        'buttonLabels': [$scope.trans.BLOCKED_NEIGHBORS],
        'addCancelButtonWithLabel': $scope.trans.ABORT,
        'androidEnableCancelButton': true, // default false
        'winphoneEnableCancelButton': true, // default false
    };

    window.plugins.actionsheet.show(options, function(index) {

        alert(index);

        switch (index) {
            case 1:
            appNavigator.pushPage('blocked_user.html', {
                animation: 'lift'
            });
            break;
        }

    });
```

will return 2 as index, while it should be 1 (worked before updating to 2.3.0)

**Comment by EddyVerbruggen** [comment]
OMG I didn't test that case. Let me do so (4 platforms to test really).

**Comment by Hirbod** [comment]
Just tested on iOS. Will fire up Android now and tell you my results

**Comment by EddyVerbruggen** [comment]
Seems like iOS is the only platform with the issue..

**Comment by Hirbod** [comment]
Confirmed. Android is working as expected.

**Comment by EddyVerbruggen** [comment]
2.3.0 is dead, long live 2.3.1, thanks for the quick test!

**Comment by Hirbod** [comment]
Confirmed! it works! Thank you very much

**Comment by lammie1971** [comment]
How can I get the action sheet to work in iOS?
