### ISSUE TITLE
2nd/3rd time using action sheet in iOS10 causes crash

### ISSUE THREAD

**Issue by jraede** [EddyVerbruggen/cordova-plugin-actionsheet#41]
I've been able to reproduce this with 100% reliability. We're using Meteor on top of Cordova so that could be an issue as well.

To reproduce, just upgrade an app to iOS 10, put it on a device with iOS 10 (only happens on device, not simulator), and open/close an action sheet. Consistently on the 2nd/3rd time it crashes with no stack trace. This happens everywhere we use the plugin.

I added some breakpoints to see where exactly it's happening - it's `[actionSheet showInView:self.webView.superview];` that's causing the crash. My hunch is it's something to do with the webview and maybe not the action sheet itself.

**Comment by EddyVerbruggen** [comment]
Hi, I wasn't able to reproduce this crash but I migrated to a newer framework class on iOS which might fix this issue. Available in 2.3.0.

Please reopen if that didn't help, but also make sure Meteor isn't the one to blame (test with a vanilla project as well).
