### ISSUE TITLE
iPhone App is crashing few times when we use Action sheets on iOS 10

### ISSUE THREAD

**Issue by krishnasarathi** [EddyVerbruggen/cordova-plugin-actionsheet#44]
Hi,

  iPhone App is crashing few times when we use Action sheets on iOS 10. Is this issue noticed earlier? If yes, when can we expect a fix for this.

Thanks,
Sarathi

**Comment by EddyVerbruggen** [comment]
Are you using version 2.3.1? Does the same happen on 2.2.2?

**Comment by krishnasarathi** [comment]
Hi,
  It's crashing on 2.2.2. I tested with 2.3.1. I don't see any crashes. Thanks for the fix.
Thanks,
Sarathi
