### ISSUE TITLE
Crash on IOS 10

### ISSUE THREAD

**Issue by eggnita** [EddyVerbruggen/cordova-plugin-actionsheet#47]
Is there any workaround to prevent the crash on ios 10 when the plugin is used 2/3 times in a row?

**Comment by EddyVerbruggen** [comment]
Do you have a way to reproduce it with the latest version and a clean Cordova CLI project? If so pleases share it and I'll take a look.

**Comment by eggnita** [comment]
It seems that I had a problem with the package upload it said version 2.3.1 but the code was from 2.2.2 ... really weird. But the problem was fixed after a complete removal of the plugin and a fresh install. I apologise for the non relevant issue reporting. Thank you for your quick reply. I will close this issue.
