### ISSUE TITLE
Center actionsheet on iPad

### ISSUE THREAD

**Issue by bash88** [EddyVerbruggen/cordova-plugin-actionsheet#49]
Hi Eddy,

Great plugin.

Since updating to the latest version after the iOS10 bug mentioned in #41 the actionsheet opens in the top left corner on iPad, because I didn't set position values. Now I'd like the sheet to open in the middle of the screen, like before. How would I go about doing this, other than inputting pixel values for both orientations?

Regards,
Bas

**Comment by kahuna76** [comment]
Yeah this is bugging me too - takes a lot of fiddling around with dynamically setting position when opening actionsheet and rotating etc. Is there a quick/easy workaround that opens it in middle as it did before ?

**Comment by kahuna76** [comment]
I am making progress - I can hide the arrow with:

`[popPresenter setPermittedArrowDirections:0];`

and I can make the left/top of the dialog go to the middle of the page with 

`popPresenter.sourceRect = CGRectMake(CGRectGetMidX(self.webView.bounds), CGRectGetMidY(self.webView.bounds),0,0);` 

but I want the middle of the dialog to be in the middle (duh) - So now I need to figure out how to get the size of the dialog and then make it offset by half that.

**Comment by geshub** [comment]
Is there a way to center actionsheet on iPad without changing the source code of the plugin ?

**Comment by geshub** [comment]
@kahuna76 Your solution worked perfectly for me, could someone integrate it in the plugin ?

**Comment by EddyVerbruggen** [comment]
Great, published in 2.3.2

**Comment by geshub** [comment]
@EddyVerbruggen Hi, just tested 2.3.2, can't find the actual centering code in the changes ?

**Comment by EddyVerbruggen** [comment]
OMG, too much 🍾 .. hang on

**Comment by EddyVerbruggen** [comment]
Version 2.3.3 is a more sober version of 2.3.2. @geshub thanks for letting me know!

**Comment by geshub** [comment]
@EddyVerbruggen Tested and worked perfectly. Thanks again !
