### ISSUE TITLE
Radio list option

### ISSUE THREAD

**Issue by paulequilibrio** [EddyVerbruggen/cordova-plugin-actionsheet#64]
First of all, thanks for this great plugin!

Would it be possible to add something as shown in these images?

[Confirmation dialogs 1](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3T29XaVRQa0QxZkk/components-dialogs-1.png)

[Confirmation dialogs 2](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3aXcyajZDN29jS1k/components-dialogs-confirmation2.png)

[Confirmation dialogs](https://material.io/guidelines/components/dialogs.html#dialogs-confirmation-dialogs)

**Comment by EddyVerbruggen** [comment]
Nope, as that's not supported by all platforms this plugin is intended for. Perhaps some other plugin would be capable of doing this.

**Comment by paulequilibrio** [comment]
I understand, thank you very much for the answer.
Again, thank you for this great plugin!
