### ISSUE TITLE
No Cancel Button on iPad

### ISSUE THREAD

**Issue by Seanmclem** [EddyVerbruggen/cordova-plugin-actionsheet#71]
Using the examples from the Readme, on an iPad
iOS: 13.5
using a config option like `addCancelButtonWithLabel: 'Cancel',`
I don't see any separated cancel button with my other buttons. There's no cancel button at all. 
Using the default position, or a manual override like `position: [20, 40],` makes no difference. Still no cancel button.
Maybe this has to do with the default position updates for iPad in 2.3.3?

**Comment by EddyVerbruggen** [comment]
Maybe it never was there, can’t remember. 

Because on ipad you can cancel by tapping anywhere outside that popover.

**Comment by Seanmclem** [comment]
It does seem to be the case that this is omitted by default on iPad in general, while still present on iPhone. Closing then... 
Thanks!
